# Generated by Django 5.0.2 on 2024-03-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_matrix', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'matrices',
            },
        ),
    ]
