# Generated by Django 5.0.2 on 2024-03-06 20:11

import main.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AlterField(
            model_name='matrix',
            name='input_matrix',
            field=main.models.MatrixField(),
        ),
    ]
