# Generated by Django 5.0.2 on 2024-03-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_test_alter_matrix_input_matrix'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrix',
            name='list_of_values',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
